version: "3.2"
services:
    betfrcodds:
        container_name: betfrcodds
        image: ppolis22/betfrcodds
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/betfrcodds
        ports:
            - "8080:8080"
        networks:
            - internal
        restart: unless-stopped
    postgres:
        container_name: betfrcodds-postgres
        image: postgres
        environment:
            POSTGRES_USER: buzz
            POSTGRES_PASSWORD: buzz
            POSTGRES_DB: betfrcodds
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres
        ports:
            - "5432:5432"
        networks:
            - internal
        restart: unless-stopped
    pgadmin:
        container_name: betfrcodds-pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "5050:80"
        networks:
            - internal
        restart: unless-stopped

networks:
    internal:
        external: true

volumes:
    postgres:
    pgadmin: